myMovieReviews/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('review.urls')),
]

myMovieReviews/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
]

myMovieReviews/review/urls.py
from django.urls import path
from .views import *

app_name = 'review'

urlpatterns = [
    path('review', review, name='review'),
    path('create', review_create, name='review_create'),
    path('detail/<int:pk>', review_detail, name='review_detail'),
    path('update/<int:pk>', review_update, name='review_update'),
    path('delete/<int:pk>', review_delete, name='review_delete'),
]

myMovieReviews/review/models.py
from django.db import models

class Review(models.Model):
  title = models.TextField()
  year = models.TextField()
  jenre = models.TextField()
  starrating = models.TextField()
  runningtime = models.IntegerField()
  content = models.TextField()
  director = models.TextField()
  actor = models.TextField()

  def formatted_runningtime(self):
    hours = self.runningtime // 60
    minutes = self.runningtime % 60
    return f"{hours}시간 {minutes}분" if hours > 0 else f"{minutes}분"

myMovieReviews/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse

def index(request):
  return render(request, 'home/index.html')

myMovieReviews/review/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Review
from django.db.models import F

def review(request):
  sort_by = request.GET.get('sort', 'title')
  valid_sort_options = ['title', 'starrating', 'runningtime']
  if sort_by not in valid_sort_options: # 유효하지 않은 값은 title로 초기화
    sort_by = 'title'
  reviews = Review.objects.order_by(F(sort_by).asc())
  for review in reviews:
    review.display_runningtime = review.formatted_runningtime()
  context = { 'reviews':reviews,
              'current_sort': sort_by,
  }
  return render(request, 'review/review.html', context)

def review_create(request):
  if request.method == 'POST':
    jenre = request.POST['jenre']
    if jenre == 'none':
      return render(request, 'review/create.html', {'error': '장르를 선택해주세요.'})
    review = Review.objects.create(
      title = request.POST['title'],
      year = request.POST['year'],
      jenre = jenre,
      starrating = request.POST['starrating'],
      runningtime = request.POST['runningtime'],
      content = request.POST['content'],
      director = request.POST['director'],
      actor = request.POST['actor'],
    )
    return redirect(reverse('review:review'))
  return render(request, 'review/create.html')

def review_detail(request, pk):
  reviews = Review.objects.get(id=pk)
  context = {
    'review':reviews,
    'display_runningtime':reviews.formatted_runningtime(),
  }
  return render(request, 'review/detail.html', context)

def review_update(request, pk):
  review = Review.objects.get(id=pk)
  if request.method == 'POST':
    jenre = request.POST.get('jenre')
    if jenre == 'none':
      return render(request, 'review/update.html', {'error': '장르를 선택해주세요.'})
    newtitle = request.POST.get('title')
    newyear = request.POST.get('year')
    newjenre = jenre
    newstarrating = request.POST.get('starrating')
    newrunningtime = request.POST.get('runningtime')
    newcontent = request.POST.get('content')
    newdirector = request.POST.get('director')
    newactor = request.POST.get('actor')
    review.title = newtitle
    review.year = newyear
    review.jenre = newjenre
    review.starrating = newstarrating
    review.runningtime = newrunningtime
    review.content = newcontent
    review.director = newdirector
    review.actor = newactor
    review.save()
    return redirect('review:review_detail', pk=review.pk)
  context = {
    'review':review
  }
  return render(request, 'review/update.html', context)

def review_delete(request, pk): # delete는 get 방식으로 받아올 수 없음
  if request.method == 'POST':
    review = Review.objects.get(id=pk)
    review.delete()
    return redirect('review:review')
  return redirect('home:index') # get 방식으로 받아올 경우 메인으로 돌아가게 함

myMovieReviews/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'index.css' %}">
  <title>Home</title>
</head>
<body>
  <header>
    <span>myMovieReviews</span>
  </header>
  <main>
    <button onclick="location.href='{% url 'review:review' %}'">시작하기</button>
  </main>
</body>
</html>

myMovieReviews/templates/review/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'create.css' %}">
  <title>My Movie reviews</title>
</head>
<body>
  <header>
    <a href="{% url 'review:review' %}" style="text-decoration: none;">
      my<span style="color: rgb(255, 100, 100);">Movie</span>reviews
    </a>
    <a href="{% url 'review:review_create' %}" style="text-decoration: none;">
      Add a New review
    </a>
  </header>
  <div class="line"></div>
  <main>
    <div class="form-container">
      <div class="form-title"><span style="color: rgb(255, 100, 100);">Movie</span>review🍿</div>
      <div class="line"></div>
      <form action="{% url 'review:review_create' %}" method="post" onsubmit="return validateForm(event)">
          {% csrf_token %}
          <div>
            <label for="title" class="form-label">제목:</label>
            <input type="text" name="title" class="form-control" id="title">
          </div>
          <div>
            <label for="year" class="form-label">개봉년도:</label>
            <input type="text" name="year" class="form-control" id="year">
          </div>
          <div>
            <label for="jenre" class="form-label">장르:</label>
            <select name="jenre" id="jenre">
              <option value="none">----------</option>
              <option value="action">액션</option>
              <option value="drama">드라마</option>
              <option value="comedy">코미디</option>
              <option value="romance">로맨스</option>
              <option value="horror">호러</option>
              <option value="sf">SF</option>
              <option value="fantasy">판타지</option>
              <option value="thriller">스릴러</option>
              <option value="adventure">어드벤쳐</option>
              <option value="animation">애니메이션</option>
              <option value="musical">뮤지컬</option>
              <option value="crime">범죄</option>
              <option value="documentary">다큐멘터리</option>
              <option value="family">가족</option>
            </select>
          </div>
          <div>
            <label for="starrating" class="form-label">별점:</label>
            <input type="text" name="starrating" class="form-control" id="starrating">
          </div>
          <div>
            <label for="runningtime" class="form-label">러닝타임:</label>
            <input type="text" name="runningtime" class="form-control" id="runningtime">
          </div>
          <div class="content-container">
            <label for="content" class="form-label">리뷰:</label>
            <textarea class="form-control" name="content" id="content" rows="6"></textarea>
          </div>
          <div>
            <label for="director" class="form-label">감독:</label>
            <input type="text" name="director" class="form-control" id="director">
          </div>
          <div>
            <label for="actor" class="form-label">배우:</label>
            <input type="text" name="actor" class="form-control" id="actor">
          </div>
          <div class="button-container">
            <button type="submit" class="btn btn-submit">Save</button>
          </div>
      </form>
    </div>
  </main>
  <script>
    function validateForm(event) {
      event.preventDefault();
      let jenre = document.getElementById('jenre').value;
      if (jenre === 'none') {
        alert('장르를 선택해주세요.');
        return false;  // 폼 제출 차단
      }
      event.target.submit();  // 폼이 유효한 경우 제출 허용
    }
  </script>
</body>
</html>

myMovieReviews/templates/review/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'detail.css' %}">
  <title>My Movie reviews</title>
</head>
<body>
  <header>
    <a href="{% url 'review:review' %}" style="text-decoration: none;">
      my<span style="color: rgb(255, 100, 100);">Movie</span>reviews
    </a>
    <a href="{% url 'review:review_create' %}" style="text-decoration: none;">
      Add a New review
    </a>
  </header>
  <div class="line"></div>
  <main>
    <div class="container">
      <div class="review">
          <div class="review-header">
            <h2 class="review-title">{{ review.title }}</h2>
            <div class="btn-container">
              <a href="{% url 'review:review_update' review.pk %}">
                <button class="btn btn-edit">수정</button>
              </a>
              <form action="{% url 'review:review_delete' review.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-delete">삭제</button>
              </form>
            </div>
          </div>
          <div class="review-body">
            <p class="review-year">
              <span class="label">개봉년도</span> {{ review.year }}
            </p>
            <p class="review-director">
              <span class="label">감독</span> {{ review.director }}
            </p>
            <p class="review-actor">
              <span class="label">주연</span> {{ review.actor }}
            </p>
            <p class="review-jenre">
              <span class="label">장르</span> {{ review.jenre }}
            </p>
            <p class="review-starrating">
              <span class="label">별점</span> {{ review.starrating }}
            </p>
            <p class="review-runningtime">
              <span class="label">러닝타임</span> {{ display_runningtime }}
            </p>
          </div>
          <div class="review-text-container">
            <p class="review-text">
              {{ review.content }}
            </p>
          </div>
      </div>
    </div>
  </main>
</body>
</html>

myMovieReviews/templates/review/review.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'review.css' %}">
  <title>My Movie reviews</title>
</head>
<body>
  <header>
    <a href="{% url 'review:review' %}" style="text-decoration: none;">
      my<span style="color: rgb(255, 100, 100);">Movie</span>reviews
    </a>
    <a href="{% url 'review:review_create' %}" style="text-decoration: none;">
      Add a New review
    </a>
  </header>
  <div class="line"></div>

  <div class="sort-container" style="display: flex; padding: 20px;">
    <span>정렬 기준:</span>
    <a href="?sort=title" class="{% if current_sort == 'title' %}active{% endif %}" style="text-decoration: none; margin-left: 10px; margin-right: 10px; font-weight: bold; color: rgb(255, 100, 100);">제목</a>
    <a href="?sort=starrating" class="{% if current_sort == 'starrating' %}active{% endif %}" style="text-decoration: none; margin-right: 10px; font-weight: bold; color: rgb(255, 100, 100);">별점</a>
    <a href="?sort=runningtime" class="{% if current_sort == 'runningtime' %}active{% endif %}" style="text-decoration: none; margin-right: 10px; font-weight: bold; color: rgb(255, 100, 100);">러닝타임</a>
  </div>

  <div class="list-container">
    {% for review in reviews %}
      <a href="{% url 'review:review_detail' review.pk %}">
        <div class="list-item">
          <div class="list-item-title">{{ review.title }}</div>
          <p class="list-item-year">
            <span class="label">개봉년도</span> {{ review.year }}
          </p>
          <p class="list-item-jenre">
            <span class="label">장르</span> {{ review.jenre }}
          </p>
          <p class="list-item-starrating">
            <span class="label">별점</span> {{ review.starrating }}
          </p>
          <p class="list-item-runningtime">
            <span class="label">러닝타임</span> {{ review.display_runningtime }}
          </p>
        </div>
      </a>
    {% empty %}
    <p>리뷰가 없습니다.</p>
    {% endfor %}
  </div>

</body>
</html>

myMovieReviews/templates/review/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'update.css' %}">
  <title>My Movie reviews</title>
</head>
<body>
  <header>
    <a href="{% url 'review:review' %}" style="text-decoration: none;">
      my<span style="color: rgb(255, 100, 100);">Movie</span>reviews
    </a>
    <a href="{% url 'review:review_create' %}" style="text-decoration: none;">
      Add a New review
    </a>
  </header>
  <div class="line"></div>
  <main>
    <div class="form-container">
      <div class="form-title"><span style="color: rgb(255, 100, 100);">Movie</span>review🍿</div>
      <div class="line"></div>
      <form action="{% url 'review:review_update' review.pk %}" method="post" onsubmit="return validateForm(event)">
          {% csrf_token %}
          <div>
            <label for="title" class="form-label">제목:</label>
            <input type="text" name="title" class="form-control" id="title" value="{{ review.title }}">
          </div>
          <div>
            <label for="year" class="form-label">개봉년도:</label>
            <input type="text" name="year" class="form-control" id="year" value="{{ review.year }}">
          </div>
          <div>
            <label for="jenre" class="form-label">장르:</label>
            <select name="jenre" id="jenre">
              <option value="none" {% if review.jenre == "none" %}selected{% endif %}>----------</option>
              <option value="action" {% if review.jenre == "action" %}selected{% endif %}>액션</option>
              <option value="drama" {% if review.jenre == "drama" %}selected{% endif %}>드라마</option>
              <option value="comedy" {% if review.jenre == "comedy" %}selected{% endif %}>코미디</option>
              <option value="romance" {% if review.jenre == "romance" %}selected{% endif %}>로맨스</option>
              <option value="horror" {% if review.jenre == "horror" %}selected{% endif %}>호러</option>
              <option value="sf" {% if review.jenre == "sf" %}selected{% endif %}>SF</option>
              <option value="fantasy" {% if review.jenre == "fantasy" %}selected{% endif %}>판타지</option>
              <option value="thriller" {% if review.jenre == "thriller" %}selected{% endif %}>스릴러</option>
              <option value="adventure" {% if review.jenre == "adventure" %}selected{% endif %}>어드벤쳐</option>
              <option value="animation" {% if review.jenre == "animation" %}selected{% endif %}>애니메이션</option>
              <option value="musical" {% if review.jenre == "musical" %}selected{% endif %}>뮤지컬</option>
              <option value="crime" {% if review.jenre == "crime" %}selected{% endif %}>범죄</option>
              <option value="documentary" {% if review.jenre == "documentary" %}selected{% endif %}>다큐멘터리</option>
              <option value="family" {% if review.jenre == "family" %}selected{% endif %}>가족</option>
            </select>
          </div>
          <div>
            <label for="starrating" class="form-label">별점:</label>
            <input type="text" name="starrating" class="form-control" id="starrating" value="{{ review.starrating }}">
          </div>
          <div>
            <label for="runningtime" class="form-label">러닝타임:</label>
            <input type="text" name="runningtime" class="form-control" id="runningtime" value="{{ review.runningtime }}">
          </div>
          <div class="content-container">
            <label for="content" class="form-label">리뷰:</label>
            <textarea class="form-control" name="content" id="content" rows="6">{{ review.content }}</textarea>
          </div>
          <div>
            <label for="director" class="form-label">감독:</label>
            <input type="text" name="director" class="form-control" id="director" value="{{ review.director }}">
          </div>
          <div>
            <label for="actor" class="form-label">배우:</label>
            <input type="text" name="actor" class="form-control" id="actor" value="{{ review.actor }}">
          </div>
          <div class="button-container">
            <button type="submit" class="btn btn-submit">Save</button>
          </div>
      </form>
    </div>
  </main>
  <script>
    function validateForm(event) {
      event.preventDefault();
      let jenre = document.getElementById('jenre').value;
      if (jenre === 'none') {
        alert('장르를 선택해주세요.');
        return false;  // 폼 제출 차단
      }
      event.target.submit();  // 폼이 유효한 경우 제출 허용
    }
  </script>
</body>
</html>