SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ideas.urls')),
    path('', include('devtools.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/devtools/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'

urlpatterns = [
  path('devtools', devtools, name='devtools'),
  path('devtools_create', devtools_create, name='devtools_create'),
  path('devtools_detail/<int:pk>', devtools_detail, name='devtools_detail'),
  path('devtools_update/<int:pk>', devtools_update, name='devtools_update'),
  path('devtools_delete/<int:pk>', devtools_delete, name='devtools_delete'),
  path('<int:pk>', devtools_detail, name='devtools_detail'),
]

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
  path('', main, name='main'),
  path('ideas_create', ideas_create, name='ideas_create'),
  path('ideas_detail/<int:pk>', ideas_detail, name='ideas_detail'),
  path('ideas_delete/<int:pk>', ideas_delete, name='ideas_delete'),
  path('ideas_update/<int:pk>', ideas_update, name='ideas_update'),
  path('<int:pk>/IdeaStar', IdeaStarToggle, name='ideas_IdeaStarToggle'),
]

SWIDEA_SITE/devtools/models.py
from django.db import models

class Devtool(models.Model):
  name = models.CharField('이름', max_length=50)
  kind = models.CharField('종류', max_length=50)
  content = models.TextField('개발툴 설명')

  def __str__(self):
    return self.name

SWIDEA_SITE/ideas/models.py
from django.db import models
from devtools.models import Devtool

class Idea(models.Model):
  title = models.CharField('아이디어명', max_length=50)
  image = models.ImageField('Image', upload_to='ideas/%Y%m%d', blank=True)
  content = models.TextField('아이디어 설명')
  interest = models.IntegerField('아이디어 관심도', default=0)
  devtool = models.ForeignKey(Devtool, null=True, on_delete=models.CASCADE, verbose_name='예상 개발툴')
  IdeaStar = models.BooleanField('찜하기', default=False)

  def __str__(self):
    return self.title

SWIDEA_SITE/devtools/forms.py
from django import forms
from .models import Devtool

class DevtoolForm(forms.ModelForm):
  class Meta:
    model = Devtool
    fields = ('__all__')

SWIDEA_SITE/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
  class Meta:
    model = Idea
    fields = ('__all__')

SWIDEA_SITE/devtools/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Devtool
from .forms import DevtoolForm

def devtools(request):
  devtools = Devtool.objects.all()
  paginator = Paginator(devtools, 8)
  page_number = request.GET.get('page')
  page_obj = paginator.get_page(page_number)
  ctx = {
    'page_obj': page_obj,
  }
  return render(request, 'devtools/devtools.html', context=ctx)

def devtools_create(request):
  if request.method == 'POST':
    devtool = Devtool.objects.create(
      name = request.POST['name'],
      kind = request.POST['kind'],
      content = request.POST['content'],
    )
    return redirect(reverse('devtools:devtools_detail', kwargs={'pk': devtool.id}))
  return render(request, 'devtools/devtools_create.html')

def devtools_detail(request, pk):
  devtools = Devtool.objects.get(id=pk)
  related_ideas = devtools.idea_set.all()
  context = {
    'devtool': devtools,
    'related_ideas': related_ideas,
  }
  return render(request, 'devtools/devtools_detail.html', context)

def devtools_update(request, pk):
  devtool = Devtool.objects.get(id=pk)
  if request.method == 'POST':
    devtool.name = request.POST.get('name')
    devtool.kind = request.POST.get('kind')
    devtool.content = request.POST.get('content')
    devtool.save()
    return redirect('devtools:devtools_detail', pk=devtool.pk)
  form = DevtoolForm(instance=devtool)
  ctx = {
    'form': form,
    'pk': pk
  }
  return render(request, 'devtools/devtools_update.html', context=ctx)

def devtools_delete(request, pk):
  Devtool.objects.get(id=pk).delete()
  return redirect('devtools:devtools')

SWIDEA_SITE/ideas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Idea
from .forms import IdeaForm

def main(request):
  ideas = Idea.objects.all()
  paginator = Paginator(ideas, 4)
  page_number = request.GET.get('page')
  page_obj = paginator.get_page(page_number)
  ctx = {
    'page_obj': page_obj,
  }
  return render(request, 'ideas/main.html', context=ctx)

def ideas_create(request):
  if request.method == 'GET':
    form = IdeaForm()
    ctx = {'form': form}
    return render(request, 'ideas/ideas_create.html', context=ctx)
  else:
    form = IdeaForm(request.POST, request.FILES)
    if form.is_valid():
      new_idea = form.save()
      return redirect(reverse('ideas:ideas_detail', kwargs={'pk': new_idea.id}))
    else:
      ctx = {'form': form}
      return render(request, 'ideas/ideas_create.html', context=ctx)

def ideas_detail(request, pk):
  target_idea = Idea.objects.get(id=pk)
  ctx = {'idea': target_idea,
          }
  return render(request, 'ideas/ideas_detail.html', context=ctx)

def ideas_delete(request, pk):
  Idea.objects.get(id=pk).delete()
  return redirect('ideas:main')

def ideas_update(request, pk):
  if request.method == 'GET':
    idea = Idea.objects.get(id=pk)
    form = IdeaForm(instance=idea)
    ctx = {'form': form,
            'pk': pk}
    return render(request, 'ideas/ideas_update.html', context=ctx)
  else:
    idea = Idea.objects.get(id=pk)
    form = IdeaForm(request.POST, request.FILES, instance=idea)
    if form.is_valid():
      form.save()
    return redirect(reverse('ideas:ideas_detail', kwargs={'pk': pk}))

def IdeaStarToggle(request, pk):
  if request.method == 'POST':
    idea = Idea.objects.get(id=pk)
    idea.IdeaStar = not idea.IdeaStar
    idea.save()
    return JsonResponse({'IdeaStar': idea.IdeaStar})
  return JsonResponse({'error': 'error'})

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content="{{ csrf_token }}" />
    <link rel="stylesheet" href="{% static 'base.css' %}" />
    {% block extra_styles %}{% endblock %}
    <title>My SW Idea</title>
  </head>
  <body>
    <nav>
      <ul>
        <li>
          <a href="{% url 'ideas:main' %}"
            >My <span class="highlight">SW Idea</span> Manage</a
          >
        </li>
        <li><a href="{% url 'ideas:ideas_create' %}">아이디어 등록</a></li>
        <li><a href="{% url 'ideas:main' %}">아이디어 관리</a></li>
        <li><a href="{% url 'devtools:devtools_create' %}">개발툴 등록</a></li>
        <li><a href="{% url 'devtools:devtools' %}">개발툴 관리</a></li>
      </ul>
    </nav>
    <div class="line"></div>
    <main>
      <div class="content">{% block content %} {% endblock %}</div>
    </main>
  </body>
</html>

SWIDEA_SITE/templates/devtools/devtools.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'devtools.css' %}" />
{% endblock %} {% block content %}
<div class="form-title"><span style="color: #a4ffa4">DevTool List</span></div>
<div class="head-text">
  개발툴 목록 페이지입니다. 자신이 사용가능한 개발툴의 목록을 확인해보세요.
</div>
<div class="content-wrapper">
  {% for devtool in page_obj.object_list %}
  <div class="item">
    <div class="info">
      <a class="name" href="{% url 'devtools:devtools_detail' devtool.pk %}"
        >{{devtool.name}}</a
      >
      <div class="kind">{{devtool.kind}}</div>
      <div class="devtool_content">{{devtool.content}}</div>
    </div>
  </div>
  <hr />
  {% endfor %}
</div>

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 처음</a>
    <a href="?page={{ page_obj.previous_page_number }}">이전</a>
    {% endif %}
    <span class="current">
      페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">다음</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">끝 &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

SWIDEA_SITE/templates/devtools/devtools_create.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'devtools_create.css' %}" />
{% endblock %} {% block content %}
<div class="form-title">
  <span style="color: #a4ffa4">DevTool Register</span>
</div>
<div class="head-text">
  개발툴 등록 페이지입니다. 자신이 다룰 수 있는 개발툴을 등록해보세요.
</div>
<form action="{% url 'devtools:devtools_create' %}" method="post">
  {% csrf_token %}
  <p>
    <label for="name" class="form-label">이름:</label>
  </p>
  <p>
    <input type="text" name="name" class="form-control" id="name" />
  </p>
  <p>
    <label for="kind" class="form-label">종류:</label>
  </p>
  <p>
    <input type="text" name="kind" class="form-control" id="kind" />
  </p>
  <p>
    <label for="content" class="form-label">개발툴 설명:</label>
  </p>
  <p>
    <textarea
      class="form-control"
      name="content"
      id="content"
      rows="6"
    ></textarea>
  </p>
  <button type="submit" class="btn btn-submit">SUBMIT</button>
</form>
{% endblock %}

SWIDEA_SITE/templates/devtools/devtools_detail.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'devtools_detail.css' %}" />
{% endblock %} {% block content %}
<div class="form-title"><span style="color: #a4ffa4">DevTool Detail</span></div>
<div class="head-text">
  개발툴 세부내용 페이지입니다. 자신이 다룰 수 있는 개발툴에 대한 상세내용을
  확인해보아요.
</div>
<div class="content-wrapper">
  <div class="info">
    <h2>{{devtool.name}}</h2>
    <p><br />{{devtool.kind}}</p>
    <div>{{devtool.content}}</div>
    <div style='width: 100%; height: 1px; background-color: gray; margin-top: 20px;'></div>
    <div class="detail--idea_list">
      <p style='font-weight: bold;'>> 만들 수 있는 SW 목록</p>
      {% for idea in related_ideas %}
      <p class='idea_title_link'><a href="{% url "ideas:ideas_detail" idea.pk %}">{{idea.title}}</a></p>
      {% endfor %}
    </div>
  </div>
</div>
<div class="btn-wrapper">
  <a
    href="{% url 'devtools:devtools_delete' devtool.pk %}"
    class="btn btn-delete"
    >삭제</a
  >
  <a href="{% url 'devtools:devtools' %}" class="btn btn-main">목록</a>
  <a
    href="{% url 'devtools:devtools_update' devtool.pk %}"
    class="btn btn-update"
    >수정</a
  >
</div>
{% endblock content %}

SWIDEA_SITE/templates/devtools/devtools_update.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'devtools_update.css' %}" />
{% endblock %} {% block content %}
<div class="form-title">
  <span style="color: #a4ffa4">DevTool Detail Update</span>
</div>
<div class="head-text">
  개발툴 세부내용 수정 페이지입니다. 개발툴에 대해 수정사항이 있으면 고쳐보아요.
</div>
<form action="{% url 'devtools:devtools_update' pk %}" method="post">
  {%csrf_token%} {{form.as_p}}
  <button type="submit" class="btn btn-submit">SUBMIT</button>
</form>
{%endblock%}

SWIDEA_SITE/templates/ideas/ideas_create.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'ideas_create.css' %}" />
{% endblock %} {% block content %}
<div class="form-title"><span style="color: #a4ffa4">Idea Register</span></div>
<div class="head-text">
  아이디어 등록 페이지입니다. 당신의 아이디어를 잊지 말고 기록하세요!
</div>
<form
  action="{% url 'ideas:ideas_create' %}"
  method="post"
  enctype="multipart/form-data"
>
  {%csrf_token%} {{form.as_p}}
  <button type="submit" class="btn btn-submit">SUBMIT</button>
</form>
{% endblock %}

SWIDEA_SITE/templates/ideas/ideas_detail.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'ideas_detail.css' %}" />
{% endblock %} {% block content %}
<div class="form-title"><span style="color: #a4ffa4">Idea Detail</span></div>
<div class="head-text">
  아이디어 세부내용 페이지입니다. 당신이 구현하려 한 아이디어들을 자세히
  살펴보세요.
</div>
<div class="content-wrapper">
  {% if idea.image.url != '' %}
  <img src="{{ idea.image.url }}" alt="제품 이미지" />
  {% else %}
  <img src="{% static 'no_img.png' %}" alt="대체 텍스트" />
  {% endif %}
  <div class="info">
    <h2>{{idea.title}}</h2>

    {% if idea.IdeaStar %}
    <button
      class="IdeaStar-btn IdeaStar"
      onclick="IdeaStarToggle(this, {{idea.id}})"
    >
      ★
    </button>
    {% else %}
    <button class="IdeaStar-btn" onclick="IdeaStarToggle(this, {{idea.id}})">
      ★
    </button>
    {% endif %}
    <meta name="csrf-token" content="{{ csrf_token }}" />

    <p>1) 아이디어 관심도<br />{{idea.interest}}</p>
    <p class="devtools_detail_link">
      2) 예상 개발 툴<br /><a
        href="{% url 'devtools:devtools_detail' idea.devtool.pk %}"
        >{{ idea.devtool }}</a
      >
    </p>
    <p>3) 아이디어 설명<br />{{idea.content}}</p>
  </div>
</div>
<div class="btn-wrapper">
  <a href="{% url 'ideas:ideas_delete' idea.pk %}" class="btn btn-delete"
    >삭제</a
  >
  <a href="{% url 'ideas:main' %}" class="btn btn-main">목록</a>
  <a href="{% url 'ideas:ideas_update' idea.pk %}" class="btn btn-update"
    >수정</a
  >
</div>
{% endblock %}
<script>
  function IdeaStarToggle(btn, id) {
    fetch(`/${id}/IdeaStar`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": document.querySelector('meta[name="csrf-token"]')
          .content,
      },
    })
      .then((response) => {
        if (!response.ok) {
          throw new Error("HTTP error " + response.status);
        }
        return response.json(); // JSON 파싱
      })
      .then((data) => {
        if (data["IdeaStar"]) btn.classList.add("IdeaStar");
        else btn.classList.remove("IdeaStar");
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  }
</script>

SWIDEA_SITE/templates/ideas/ideas_update.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'ideas_update.css' %}" />
{% endblock %} {% block content %}
<div class="form-title">
  <span style="color: #a4ffa4">Idea Detail Update</span>
</div>
<div class="head-text">
  아이디어 세부내용 수정 페이지입니다. 아이디어를 구체화하거나 내용을 변경해
  보아요.
</div>
<form
  action="{% url 'ideas:ideas_update' pk %}"
  method="post"
  enctype="multipart/form-data"
>
  {%csrf_token%} {{form.as_p}}
  <button type="submit" class="btn btn-submit">SUBMIT</button>
</form>
{%endblock%}

SWIDEA_SITE/templates/ideas/main.html
{% extends 'base.html' %} {% load static %} {% block extra_styles %}
<link rel="stylesheet" href="{% static 'main.css' %}" />
{% endblock %} {% block content %}
<div class="form-title"><span style="color: #a4ffa4">Idea List</span></div>
<div class="head-text">나의 아이디어를 잊지 말고 기록해보세요</div>
<div class="content-wrapper">
  {% for idea in page_obj.object_list %}
  <div class="item">
    <div class="image-container">
      {% if idea.image != null and idea.image.url != "" %}
      <img src="{{ idea.image.url }}" alt="대체 텍스트" />
      {% else %}
      <img src="{% static 'no_img.png' %}" alt="대체 텍스트" />
      {% endif %}
      <div class="IdeaStar-icon">
        <button
          class="btn_IdeaStar"
          data-id="{{ idea.id }}"
          data-IdeaStar="{{ idea.is_IdeaStar|yesno:'IdeaStar,not-IdeaStar' }}"
        >
          {% if idea.is_IdeaStar %} ★ {% else %} ☆ {% endif %}
        </button>
      </div>
    </div>
    <div class="info">
      <a class="title" href="{% url 'ideas:ideas_detail' idea.pk %}"
        >{{idea.title}}</a
      >
      <div class="item-line"></div>
      <p class="devtool">예상 개발 툴: {{idea.devtool}}</p>
      <p class="interest">
        아이디어 관심도:
        <button class="btn_interest btn_plus">+</button>
        {{idea.interest}}
        <button class="btn_interest btn_minus">-</button>
      </p>
    </div>
  </div>
  {% endfor %}
</div>

<input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; 처음</a>
    <a href="?page={{ page_obj.previous_page_number }}">이전</a>
    {% endif %}
    <span class="current">
      페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">다음</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">끝 &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock %}
<script>
  function IdeaStarToggle(btn, id) {
    fetch(`/${id}/IdeaStar`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": document.querySelector('meta[name="csrf-token"]')
          .content,
      },
    })
      .then((response) => {
        if (!response.ok) {
          throw new Error("HTTP error " + response.status);
        }
        return response.json(); // JSON 파싱
      })
      .then((data) => {
        if (data["IdeaStar"]) btn.classList.add("IdeaStar");
        else btn.classList.remove("IdeaStar");
      })
      .catch((error) => {
        console.error("Error:", error);
      });
  }
</script>