piro22_Ajax_Pirostagram/comments/urls.py
from django.urls import path
from .views import *

app_name = 'comments'

urlpatterns = [
    path('comment/<int:pk>/create', comment_create, name='comment_create'),
    path('comment/<int:pk>', comment_delete, name='comment_delete'),
]

piro22_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pirostagrams.urls')),
    path('', include('comments.urls')),
]

piro22_Ajax_Pirostagram/pirostagrams/urls.py
from django.urls import path
from .views import *

app_name = 'pirostagrams'

urlpatterns = [
    path('', pirostagram, name='pirostagram'),
    path('post_new/', post_new, name='post_new'),
    path('post/<int:pk>', post, name='post'),
    path('like_ajax/', like_ajax, name='like_ajax'),
]

piro22_Ajax_Pirostagram/comments/models.py
from django.db import models
from pirostagrams.models import Post

class Comment(models.Model):
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)

piro22_Ajax_Pirostagram/pirostagrams/models.py
from django.db import models

class Post(models.Model):
  content = models.TextField(default="내용을 입력하세요")
  like = models.IntegerField(default=0)

piro22_Ajax_Pirostagram/pirostagrams/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

piro22_Ajax_Pirostagram/comments/views.py
from django.shortcuts import redirect
from .models import Post
from .models import Comment

def comment_create(request, pk):
  if request.method == 'POST':
    findPost = Post.objects.get(id=pk)
    Comment.objects.create(
      post = findPost,
      content = request.POST['content']
    )
    return redirect('pirostagrams:post', pk=findPost.id)
  
def comment_delete(request, pk):
  if request.method == 'POST':
    findComment = Comment.objects.get(id=pk)
    post_pk = findComment.post.id
    findComment.delete()
    return redirect('pirostagrams:post', pk=post_pk)

piro22_Ajax_Pirostagram/pirostagrams/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from comments.models import Comment

def pirostagram(request):
  posts = Post.objects.all()
  ctx = {
      'posts': posts,
  }
  return render(request, 'pirostagram.html', ctx)

def post_new(request):
  if request.method == 'POST':
      form = PostForm(request.POST)
      if form.is_valid():
          form.save()
          return redirect('pirostagrams:pirostagram')
      else:
          ctx = {
              'form': form,
          }
          return render(request, 'post_new.html', ctx)
  elif request.method == 'GET':
      form = PostForm()
      ctx = {
          'form': form,
      }
      return render(request, 'post_new.html', ctx)

def post(request, pk):
  posts = Post.objects.get(id=pk)
  comments = Comment.objects.filter(post=posts)
  ctx = {
      'post': posts,
      'comment': comments,
  }
  return render(request, 'post.html', ctx)

from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json

@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)
    post_id = req['id']
    button_type = req['type']

    post = Post.objects.get(id=post_id)

    post.like += 1
    
    post.save()

    return JsonResponse({'id': post_id, 'type': button_type})

piro22_Ajax_Pirostagram/templates/pirostagram.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'reset.css' %}">
  <link rel="stylesheet" href="{% static 'pirostagram.css' %}">
  <title>Pirostagram</title>
</head>
<body>
  <div class="container">
    <header class="header">
      <button>
        <img src="../static/goBack.svg" alt="뒤로 가기 버튼">
      </button>
      <div class="header__username">Pirogramming</div>
      <div class="header__rightButtons">
        <button><img src="../static/alarm.svg" alt="알림 버튼"></button>
        <button><img src="../static/more.svg" alt="더보기 버튼"></button>
      </div>
    </header>
  <main>
    <section class="profile">
      <div class="profile__image">
        <img src="../static/profilePicture.png" alt="프로필 사진" />
      </div>
      <div class="profile__data">
        <div class="profile__data-item">
          <div class="profile__data-number">1,234</div>
          <div class="profile__data-type">Posts</div>
        </div>
        <div class="profile__data-item">
          <div class="profile__data-number">5,678</div>
          <div class="profile__data-type">Followers</div>
        </div>
        <div class="profile__data-item">
          <div class="profile__data-number">9,101</div>
          <div class="profile__data-type">Following</div>
        </div>
      </div>
    </section>
    <section class="userInfo">
      <div>
        <div class="userInfo__username">Pirogramming</div>
        <div class="userInfo__category">컴퓨터 회사</div>
        <div class="userInfo__description">프로그래밍의 첫 걸음, 피로그래밍</div>
      </div>
      <button class="userInfo__follow">Follow</button>
    </section>
    <aside class="highlights">
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
      <div class="highlights__item">
        <button class="highlights__item-image">
          <img src="../static/profilePicture.png">
        </button>
        <div class="highlights__item-title">Text here</div>
      </div>
    </aside>
    <section class="posts">
      <nav class="posts__tabBar">
        <div class="posts__tab posts__tab--selected">1</div>
        <div class="posts__tab">2</div>
        <div class="posts__tab">3</div>
      </nav>
      <article class="posts__contents">
        {% for post in posts %}
          <div class="posts__photo card post__container post-id-{{ post.id }}">
            <a href="{% url 'pirostagrams:post' post.id %}">
              <img src="{% static 'img_lights.jpg' %}" alt="...">
            </a>
          </div>
        {% endfor %}
      </article>
    </section>
  </main>
  <footer>
    <button class="navBar">1</button>
    <button class="navBar">2</button>
    <button class="navBar">3</button>
    <button class="navBar">4</button>
    <button class="navBar navBar--selected">5</button>
  </footer>
  </div>
</body>
</html>

piro22_Ajax_Pirostagram/templates/post.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'reset.css' %}">
  <link rel="stylesheet" href="{% static 'post.css' %}">
  <title>Pirostagram</title>
</head>
<body>
  <div class="container">
    <header class="header">
      <button>
        <img src="../static/goBack.svg" alt="뒤로 가기 버튼">
      </button>
      <div class="header__username">Pirogramming</div>
      <div class="header__rightButtons">
        <button><img src="../static/alarm.svg" alt="알림 버튼"></button>
        <button><img src="../static/more.svg" alt="더보기 버튼"></button>
      </div>
    </header>
    <main>
      <section class="post">
        <div class="card post__container post-id-{{ post.id }}">
          <div class="card-body">
              <div class="post__img">
                  <img src="{% static 'img_lights.jpg' %}" alt="..." style="width:100%">
              </div>
              <div class="card-text">{{ post.content }}</div>
              <div class="btn btn-primary post__like" style="width: 35px; margin-top: 10px; background-color: gray; cursor: pointer;" onclick="onClickLike({{ post.id }}, 'like')">Like {{ post.like }}</div>
          </div>
          
          <div class="comments-section">
            <div class="comments-title" style="margin-top: 20px;"><댓글></div>
            {% for comments in comment %}
                <div class="comment-card">
                    <div class="comment-card-body">
                        <div style="margin-top: 10px; margin-left: 10px; color: black;">{{ comments.content }}</div>
                        <div class="comment-date">{{ comments.created_at }}</div>
                    </div>
                    <form
                    action="{% url 'comments:comment_delete' comments.pk %}"
                    class="mb-0"
                    method="post">
                            {% csrf_token %}
                        <button
                            type="submit"
                            class="btn btn-outline-danger btn-sm delete-btn"
                            style="font-size: 10px; margin-left: 10px;"
                        >
                            댓글 삭제
                        </button>
                    </form>
                </div>
                {% empty %}
                    <p>댓글이 없습니다</p>
                {% endfor %}
          </div>

          <form class="comment-form" action="{% url 'comments:comment_create' post.id %}" method="post">
              {% csrf_token %}
              <textarea
                      class="form-control"
                      rows="4"
                      name="content"
                      placeholder="댓글을 입력하세요"
              ></textarea>
              <br><button type="submit" class="submit-btn">댓글 작성</button>
          </form>

        </div>
      </section>
    </main>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
      const onClickLike = async(id, type) => {
          const url = "/like_ajax/";
          const { data } = await axios.post(url, {
              id,
              type,
          });
          likeHandResponse(data.id, data.type);
      }
  
      const likeHandResponse = (id, type) => {
          const element = document.querySelector(`.post-id-${id} .post__${type}`);
          const originHTML = element.innerHTML;
          const [buttonType, num] = originHTML.split(" ");
          const count = Number(num) + 1;
  
          element.innerHTML = `${buttonType} ${count}`;
      }
  </script>
</body>
</html>

piro22_Ajax_Pirostagram/templates/post_new.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'reset.css' %}">
  <link rel="stylesheet" href="{% static 'post_new.css' %}">
  <title>Pirostagram</title>
</head>
<body>
<div class="form__container">
  <form action="" method="POST">
      {% csrf_token %}
      <table>
          {{ form.as_table }}
      </table>

      <input type="submit" value="submit">
  </form>
</div>
</body>
</html>